name: Publish Quarto site to gh-pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      # Keep if you might execute Python later; otherwise you can remove it.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 1) Render site, but DO NOT execute code chunks (avoids package errors)
      - name: Render site
        run: quarto render --no-execute

      # 2) Publish to gh-pages (creates the branch if it doesn't exist)
      - name: Publish to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          quarto publish gh-pages --no-prompt
